# During shutdown,journald and umount.target are in conflict due to 
# which mount failure logs are logged on console.
# so adding below entry to systemd-journal-flush.service, to stop  
# service, when system starts to unmount.
[Unit]
Conflicts=umount.target
