# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

name: "Stable specs and manifests checkout"
description: "Checks out the repo, and a stable version of both specs and manifests."
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 #v7.0.0
      with:
        fetch-depth: 0
        fetch-tags: true
        persist-credentials: false

    - name: Checkout stable specs and manifests
      shell: bash
      run: git checkout origin/26.06 -- SPECS/ toolkit/resources/manifests/package/*.txt
