# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
---
name: Static glibc version check

on:
  pull_request:
    branches: [main, 3.0, 3.0-dev]
    types: [opened, synchronize, reopened]
    paths:
      - .github/workflows/check-static-glibc.yml
      - '**.spec'

permissions: read-all

jobs:
  spec-check:
    name: Static glibc version check
    runs-on: ubuntu-latest

    steps:
      # Checkout the branch of our repo that triggered this action
      - name: Workflow trigger checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      # For consistency, we use the same major/minor version of Python that Azure Linux ships
      - name: Setup Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Get Python dependencies
        run: python3 -m pip install -r toolkit/scripts/requirements.txt

      - name: Verify .spec files
        run: python3 toolkit/scripts/check_static_glibc.py SPECS/**/*.spec SPECS-EXTENDED/**/*.spec SPECS-SIGNED/**/*.spec
