# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# This action checks that the licenses.json file is up-to-date
# and that the LICENSES-MAP.md file is up-to-date
name: Spec License Map Check

on:
  pull_request:
    branches: [3.0*]
    types: [opened, synchronize, reopened]
    paths:
      - .github/workflows/check-license-map.yml
      - '**.spec'

permissions: read-all

jobs:
  check:
    name: Spec License Map Check
    runs-on: [ ubuntu-latest ]

    steps:
      # Checkout the branch of our repo that triggered this action
      - name: Workflow trigger checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          
      - name: Setup Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Get Python dependencies
        run: python3 -m pip install python-rpm-spec

      - name: Run license map checking script
        run: |
          python3 ./toolkit/scripts/license_map.py \
          ./LICENSES-AND-NOTICES/SPECS/data/licenses.json \
          ./LICENSES-AND-NOTICES/SPECS/LICENSES-MAP.md \
          ./SPECS \
          ./SPECS-EXTENDED \
          ./SPECS-SIGNED
