# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
---
name: Github Merge Conflict Check

on:
  pull_request:
    branches: [main, 3.0*]

permissions: read-all

jobs:
  spec-check:
    name: Github Merge Conflict Check
    runs-on: ubuntu-latest

    steps:
      # Checkout the branch of our repo that triggered this action
      - name: Workflow trigger checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Get base commit for PRs
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          base_ref="${BASE_REF}"
          git fetch origin $base_ref
          echo "base_sha=$(git rev-parse origin/$base_ref)" >> $GITHUB_ENV
          echo "Merging ${{ github.sha }} into $base_ref"
        env:
          BASE_REF: ${{ github.base_ref }}

      - name: Get base commit for Pushes
        if: ${{ github.event_name == 'push' }}
        run: |
          git fetch origin ${{ github.event.before }}
          echo "base_sha=${{ github.event.before }}" >> $GITHUB_ENV
          echo "Merging ${{ github.sha }} into ${{ github.event.before }}"

      - name: Check for merge conflicts
        run: |
          echo "Files changed: '$(git diff-tree --no-commit-id --name-only -r ${{ env.base_sha }} ${{ github.sha }})'"
          changed_files=$(git diff-tree --diff-filter=d --no-commit-id --name-only -r ${{ env.base_sha }} ${{ github.sha }})

          merge_conflict_found=false
          for file in $changed_files ; do
            if [ -f $file ]; then
              echo "Checking for merge conflicts in $file"
              if grep -H -r "^<<<<<<< HEAD$" $file; then
                echo "Merge conflict found in $file"
                merge_conflict_found=true
              fi

              if grep -H -r "^>>>>>>>$" $file; then
                echo "Merge conflict found in $file"
                merge_conflict_found=true
              fi

              if grep -H -r "^=======$" $file; then
                echo "Merge conflict found in $file"
                merge_conflict_found=true
              fi
            fi
          done

          if [[ $merge_conflict_found =~ [Tt]rue ]]; then
            echo "Merge conflict found in one or more files"
            exit 1
          fi
