# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: MIT
---
name: GitHub Actions Security Analysis with zizmor 🌈

on:
  pull_request:
    branches: [3.0*,next,26.06*]

permissions: {}

jobs:
  run-zizmor-scan:
    name: Run Zizmor scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      ZIZMOR_VERSION: 1.5.2
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0

      - name: Run zizmor 🌈
        run: uvx zizmor=="$ZIZMOR_VERSION" "$GITHUB_WORKSPACE" --format sarif > zizmor_scan_report.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@8aad20d150bbac5944a9f9d289da16a4b0d87c1e  # v4.36.2
        with:
          sarif_file: zizmor_scan_report.sarif
